#site.XX(attributes)
#site head left
title: Hello, welcome to my homepage !


#contact information
avatar: /logo.png
author: Xuanbai Chen
email: xuanbaic@andrew.cmu.edu
location: Haidian, Beijing, China

#current position
subscribe: True

#footer
description: A personal website for recording and posting the significant events in my life.

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme

#every page number
paginate: 10

remote_theme: ngzhio/jekyll-theme-hamilton
# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
#google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
#disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: logo.png

social:
  name: Xuanbai Chen
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/Xuanbai-Chen

google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
